# Generated by Django 2.2 on 2020-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('author', models.CharField(default='Unknown', max_length=40, verbose_name='Автор')),
                ('category', models.CharField(choices=[('other', 'Розное'), ('food', 'Еда'), ('it', 'IT-сфера'), ('psycho', 'Психология'), ('bikers', 'Велосипеды')], default='other', max_length=20, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
