# Generated by Django 2.2 on 2020-08-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_article_tags'),
        ('webapp', '0006_auto_20200811_2105'),
    ]

    operations = [
    ]
